# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include ::CommonMetadata

  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = CollectionIndexer
end
